# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  #vm配置的可以理解为操作系统版本，也就是使用的安装镜像image
  config.vm.box = "centos/7"
  #系统的hostname
  config.vm.hostname = "centos1.example.com"
  #网络，有好多种
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos1"
    vb.memory = 512
    vb.cpus = 1
    #虚拟机有时候解析不了dns，要加上这一句，不知道是怎么回事
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
