# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  #vm配置的可以理解为操作系统版本，也就是使用的安装镜像image
  config.vm.box = "centos/7"
  #系统的hostname
  config.vm.hostname = "centos1.example.com"
  #网络，有好多种
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true
  # set auto_update to false, if you do NOT want to check the correct
  # additions version when booting this machine
  config.vbguest.auto_update = false

  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos1"
    vb.memory = 512
    vb.cpus = 1
    #虚拟机有时候解析不了dns，要加上这一句，不知道是怎么回事
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
