ENV['VAGRANT_NO_PARALLEL'] = ''

Vagrant.configure("2") do |config|
  config.vm.define "nfs" do |nfs|
    nfs.vm.box = "ubuntu/xenial6"
    nfs.vm.hostname = "nfs.example.com"
    nfs.vm.network "public_network", ip: "192.168.50.110"
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
    nfs.vm.provider "virtualbox" do |v|
      v.name = "nfs"
      v.memory = 512
      v.cpus = 1
    end
  end
  config.vm.provision "shell", path: "bootstrap.sh"
end
