# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  # Kubernetes Master Server
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "kmaster.example.com"
    kmaster.vm.network "public_network", ip: "192.168.50.150"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 4096
      v.cpus = 2
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    # kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "public_network", ip: "192.168.50.15#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 2048
        v.cpus = 2
        # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end

end
