# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "bootstrap.sh"
  #vm配置的可以理解为操作系统版本，也就是使用的安装镜像image
  config.vm.box = "centos/7"
  #系统的hostname
  config.vm.hostname = "vagranttest.example.com"
  #网络，有好多种
  config.vm.network "private_network", ip: "172.42.42.110"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagranttest"
    vb.memory = 2048
    vb.cpus = 2
    #虚拟机有时候解析不了dns，要加上这一句，不知道是怎么回事
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
